// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCH-ba4PK1YcZ5X7xxKGx8Gymr30MEzTU',
    appId: '1:132878670152:web:1a0ea429fa2ce508867b7d',
    messagingSenderId: '132878670152',
    projectId: 'chore-hunter-9a6bd',
    authDomain: 'chore-hunter-9a6bd.firebaseapp.com',
    storageBucket: 'chore-hunter-9a6bd.appspot.com',
    measurementId: 'G-JYQ7Y174EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTRqYEfqokSj4v6eHEiblfVVk38PB-uc',
    appId: '1:132878670152:android:21b4e45624e78b24867b7d',
    messagingSenderId: '132878670152',
    projectId: 'chore-hunter-9a6bd',
    storageBucket: 'chore-hunter-9a6bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKPpG1MNzaJiZ_yM80RSGfFG4G2tL1g68',
    appId: '1:132878670152:ios:d7e331c7a3b6e92b867b7d',
    messagingSenderId: '132878670152',
    projectId: 'chore-hunter-9a6bd',
    storageBucket: 'chore-hunter-9a6bd.appspot.com',
    iosClientId: '132878670152-419alui2ph86hhtpa4fa85h8edlfb9oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chorehunter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKPpG1MNzaJiZ_yM80RSGfFG4G2tL1g68',
    appId: '1:132878670152:ios:d7e331c7a3b6e92b867b7d',
    messagingSenderId: '132878670152',
    projectId: 'chore-hunter-9a6bd',
    storageBucket: 'chore-hunter-9a6bd.appspot.com',
    iosClientId: '132878670152-419alui2ph86hhtpa4fa85h8edlfb9oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chorehunter',
  );
}
